New log file opened at Tue Apr 28 11:05:00 CEST 2015 by 9636@Henrik-Dator
Taking next connection to: 49741
New client attempting to connect on port: 49752-49741
  Address = /130.237.241.133:49741
This client on port 49752 has uuid 86c6a036-c0b6-415f-9454-4e502aee449c configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-86c6a036-c0b6-415f-9454-4e502aee449c
Taking next connection to: 49741
New client attempting to connect on port: 50258-49741
  Address = /130.237.241.133:49741
Handshake exception on socket: 50258
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49741
New client attempting to connect on port: 50259-49741
  Address = /130.237.241.133:49741
This client on port 50259 has uuid aa1869d4-89e1-4af1-813d-4b651744a6cc configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-86c6a036-c0b6-415f-9454-4e502aee449c, play-fork-run-aa1869d4-89e1-4af1-813d-4b651744a6cc
Taking next connection to: 49741
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49741
